env:
  es6: true
  browser: true
  jquery: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: next
  eol-last:
    - error
    - always
  class-methods-use-this: 0
  func-names: 0
  no-console: 0
